docs/content/1.getting-started/4.shortcuts.md
Adds detail on how to configure a shortcut with `defineShortcuts`.
It might need a bit of rewording, but the essential is here. Feel free to edit the PR.
=> docs(shortcuts): add config details

README.md, docs/content/1.getting-started/1.index.md, docs/content/1.getting-started/3.theming.md, docs/content/3.forms/4.select-menu.md
Updated "Tailwind CSS" and "Headless UI" to the preferred naming [as stated by its creator](https://twitter.com/adamwathan/status/1489245425265692679)
=> docs: use preferred naming for Tailwind CSS

docs/content/1.getting-started/3.theming.md
Update install commands in theming documentation for customizing iconify pack based on installation steps from https://github.com/egoist/tailwindcss-icons
=> docs: update icon theming installation commands

src/runtime/components/elements/AvatarGroup.ts, src/runtime/components/elements/ButtonGroup.ts
```vue
<UButtonGroup size="md">
<UButton
v-for="type in ['One', 'Two', 'Three']"
:key="type"
:label="type"
color="white"
/>
</UButtonGroup>
```
Currently this fails, since the first child of ButtonGroup will be a Fragment.
=> fix(ButtonGroup/AvatarGroup): allow `v-for`

docs/components/content/prose/ProseCode.vue
=> docs: fix copy button overlap code content

docs/content/5.overlays/6.notification.md, src/runtime/app.config.ts, src/runtime/components/overlays/Notifications.vue
Resolves #185 
Instead of using `notifications.wrapper`, add `notifications.position` and `notifications.width` for better control without having to copy the whole classes:
```ts [app.config.ts]
export default defineAppConfig({
ui: {
notifications: {
// Show toasts at the top right of the screen
position: 'top-0 right-0'
}
}
})
```
=> feat(notifications): simplify how to position them

docs/components/docs/DocsFooter.vue
=> docs: LogoLabs not shown

docs/content/1.getting-started/3.theming.md, docs/content/2.elements/1.avatar.md, docs/content/2.elements/3.button.md, docs/content/3.forms/1.input.md, docs/content/3.forms/3.select.md, docs/content/3.forms/4.select-menu.md, docs/content/4.navigation/2.command-palette.md, src/runtime/app.config.ts, src/runtime/components/navigation/CommandPalette.vue
=> chore(CommandPalette): handle loading state

docs/components/docs/DocsPageHeader.vue, docs/content/3.forms/8.form-group.md
One of the recent new components has a `.ts` ending instead of `.vue`, which resulted in a 404 when clicking the button in the documentation.
This Pro adds support for setting a file ending other than `.vue` if needed.
=> docs(github, button): support for various file extensions

docs/components/content/examples/TableExampleEmptySlot.vue, docs/content/4.data/1.table.md, src/runtime/components/data/Table.vue
This feature allows for customizable content, including custom text, images, or components, to create a meaningful and visually appealing message when the table is empty.
=> feat(table): add slot for empty state

docs/components/ThemeSelect.vue, docs/components/content/ComponentCard.vue, src/runtime/app.config.ts, src/runtime/components/forms/Checkbox.vue, src/runtime/components/forms/Input.vue, src/runtime/components/forms/Radio.vue, src/runtime/components/forms/Select.vue, src/runtime/components/forms/SelectMenu.vue, src/runtime/components/forms/Textarea.vue
Resolves #276 
- `ui.custom` has been removed in favor of `class` with `$attrs` bound to form elements.
- `class` will no longer apply on the wrapper but on the element so use `:ui="{ wrapper: '...' }"`
=> fix(forms)!: bind `$attrs` to elements

src/runtime/components/data/Table.vue
If you use the selection, the number of columns of the empty and loading slot is wrong.
=> fix(Table): colspan of `empty` and `loading` is wrong when selection enabled

src/runtime/components/forms/Input.vue, src/runtime/components/forms/Select.vue, src/runtime/components/forms/Textarea.vue
This commit updates the onInput event handler code. The type assertion in the code has been modified to cast event.target as HTMLInputElement instead of any. By using the specific HTMLInputElement type, we ensure accurate type checking and maintain type safety throughout the codebase. The event handler still emits the 'update:modelValue' event and updates the model value based on the input element's value. This modification enhances code clarity and provides more precise typing, leading to better code quality.
=> fix(forms): precise type assertion for `onInput` event handler

package.json
Added the `lint:fix` command, which is essential for resolving any eslint rule issues that may arise after completing the code.
=> chore: add `lint:fix` command 

docs/components/content/examples/AccordionExampleBasic.vue, docs/content/2.elements/5.accordion.md, src/runtime/components/elements/Accordion.vue, src/runtime/utils/StateEmitter.ts
Resolves #362 
Resolves #356
This PR adds to the `Accordion` component an additional mode of operation where you can customize the closing of panels when a specific list item is opened or global closing of panels whenever 1 list item is open.
=> feat(Accordion): add `multiple` prop and close others by default 

src/runtime/components/forms/Range.vue
When specifying a non-zero value (including positive or negative numbers), the range progress bar style has issues, as shown on the left side of the following picture. The version on the right has been fixed.
=> fix(Range): progress style

docs/content/1.getting-started/2.installation.md
Good to have an example of the "ui" key here. It's repeated later in the docs.
=> docs: add `nuxt.config.ts` `ui` entry example

docs/content/3.forms/3.select.md
Wanted to add this detail to the docs. I found it by chance passing the proper object into the options prop and thought it might be helpful to people searching the docs.
=> docs(Select): disable single select options

docs/content/1.getting-started/2.installation.md
Change all `settings.json` matches with ` .vscode/settings.json` to make it more explicit and clear like in [Nuxt Tailwind Docs](https://tailwindcss.nuxtjs.org/tailwind/editor-support)
=> docs: explicit settings.json path

src/runtime/components/elements/Avatar.vue
Closes #351 
Left the props `src` and `alt` explicitly defined as they're used in more areas than just as attributes.
I struggled with my editor auto formatting files so I logged #420
=> feat(Avatar)!: bind component attributes to img element

docs/content/4.data/1.table.md, src/runtime/components/data/Table.vue
Currently if you select all items in a table with the header checkbox and attempt to deselect a row by clicking on the row itself and not the checkbox, that row will be deleted from the rows prop. I believe this was caused by the @change because selected was being set to rows itself.
Switched to calling onSelect for all rows in a foreach when selecting all rows, so that that handler in the parent component can remove the item without removing it from rows.
I apologize in advance for any hiccups, this is my first PR ever (I'm a solo dev). 
Mahalo!
=> fix(Table): fixed row deletion bug on deselect

docs/components/content/examples/SelectMenuExampleAsyncSearch.vue, docs/content/3.forms/4.select-menu.md, src/runtime/components/forms/SelectMenu.vue
Resolves #384 
Add the possibility to set a `searchFunction` as prop to allow the user to have complete control of the way options are filtered.
This function can be either synchronous or asynchronous.
Let me know what you think 🙂
=> feat(SelectMenu): handle async search

src/runtime/components/navigation/CommandPaletteGroup.vue
This PR fixes a problem where slots in the UCommandPalette component could not be accessed in the `active` and `selected` states.
=> feat(CommandPalette): bind active and selected to scoped slot

docs/components/content/examples/PopoverExampleMode.vue, docs/content/6.overlays/3.popover.md, src/runtime/components/overlays/Popover.vue
use `popover.value?.$.provides`
not `trigger.value?.$.provides`
=> fix(Popover): hover mode

docs/content/1.getting-started/2.installation.md
Fix a slight error in the documentation under `Getting Started > Installation > IntelliSense`.
=> docs(installation): fix incorrectly placed comma in array

docs/components/content/examples/FormExampleJoi.vue, docs/components/content/examples/FormExampleYup.vue, docs/components/content/examples/FormExampleZod.vue, docs/content/3.forms/10.form.md, src/runtime/components/forms/Form.ts
@benjamincanac Spotted a few issues in the last examples in the docs.
=> fix(Form): return state on validate

docs/app.vue, docs/content/1.getting-started/3.theming.md, src/module.ts, src/runtime/app.config.ts, src/runtime/plugins/colors.ts, src/runtime/ui.css
This PR adds a `DEFAULT` shade to the `primary` color that is bound to a `--color-primary-DEFAULT` CSS variable.
This CSS variable changes between light and dark mode to `--color-primary-500` and `--color-primary-400` respectively.
=> feat(module): add `DEFAULT` shade to `primary` color

docs/components/content/examples/TabsExampleChange.vue, docs/components/content/examples/TabsExampleVModel.vue, docs/content/5.navigation/4.tabs.md, src/runtime/components/navigation/Tabs.vue
=> feat(Tabs): control selected index

src/runtime/components/forms/Form.ts
Fixes #492
I used safeParseAsync to avoid the need for the try-catch.
=> fix(Form): use safeParseAsync for zod

.eslintrc.cjs, docs/components/content/examples/TableExampleAdvanced.vue, docs/components/content/examples/TabsExampleItemCustomSlot.vue, docs/components/content/examples/TabsExampleItemSlot.vue
Added Eslint for spaceing 
1. `vue/comma-spacing` 
```vue
<template>
<UBreadcrumb :items="items">
<template #item="{ item,isActive,index }">
// ...
</template>
</UBreadcrumb>
</template>
<template>
<UBreadcrumb :items="items">
<template #item="{ item, isActive, index }">
// ...
</template>
</UBreadcrumb>
</template>
```
2. `no-multi-spaces`
```js
// before
// 👇 
const accountForm = reactive({ name: 'Benjamin', username: 'benjamincanac'  })
//  after
// 👇 
const accountForm = reactive({ name: 'Benjamin', username: 'benjamincanac' })
```
=> chore: add eslint rules for spacing

docs/content/3.forms/10.form.md, docs/content/3.forms/9.form-group.md
Pretty simple fix, I just noticed there was a typo in file extensions.
=> docs: dead links in `Form` and `FormGroup` pages

src/runtime/components/forms/Form.vue
=> fix(Form): fix `getValibotError` to avoid importing `safeParseAsync`

docs/components/Header.vue
=> docs: add examples link in header

src/runtime/app.config.ts
The `::-moz-slider-runnable-track` pseudo-element is not valid, so it should be replaced with [`::-moz-range-track`](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-range-track).
This solves the issue with the track background in Firefox:
| **Before** | **After** |
|--------|--------|
| <img width="527" alt="Screen Shot 2023-09-09 at 01 58 07@2x" src="https://github.com/nuxt/ui/assets/6909744/cbd45a74-3061-480d-87b8-4b90dd9f2029"> | <img width="520" alt="Screen Shot 2023-09-09 at 02 06 26@2x" src="https://github.com/nuxt/ui/assets/6909744/612ba3fb-db7e-4244-b4d2-7a8efac85318"> |
=> fix(Range): fix track pseudo-elements for mozilla

src/runtime/components/data/Table.vue
resolve #646 
If the table doesn't add select listener, `onSelect` will return. So just select all manually.
=> fix(Table): select all rows without select listener

src/runtime/components/forms/FormGroup.vue
Fixes #621 
The problem was caused by input click events being handled by the `<label>` which sets focus to the nested input. This creates issues with interactive components like SelectMenu, where selecting a value triggers both the component to close and the label to open it.
Here is a reproduction: https://stackblitz.com/edit/nuxt-ui-xj1xrv?file=app.vue
=> fix(FormGroup): prevent input click from propagating to label

src/runtime/types/tabs.d.ts
Docs shows examples with possible custom keys in the items objects, but type actually forbids it, so I've added it. https://ui.nuxt.com/navigation/tabs#slots
=> fix(Tabs): allow custom keys in `TabItem`

src/runtime/components/elements/Accordion.vue
#626
The `closeOther` function, which closes items by index in ascending order (1, 2, 3, 4, etc.), can lead to a bug when users try to close items using the keyboard. To solve this issue, we need to close open items in a circular order. Here's an example:
1. When the `currentIndex` is `0`, close items in the order 2, 3, 4, `1`.
2. When the `currentIndex` is `1`, close items in the order 3, 4, 0, `2`.
3. When the `currentIndex` is `2`, close items in the order 4, 0, 1, `3`.
4. When the `currentIndex` is `3`, close items in the order 0, 1, 2, `4`.
5. When the `currentIndex` is `4`, close items in the order 1, 2, 3, `0`.
**Befor :**
https://github.com/nuxt/ui/assets/37311945/5906d35f-c6b2-455b-a8c1-f2b458cc4b8f
**After:** 
https://github.com/nuxt/ui/assets/37311945/e536d1cd-db05-4780-80be-d70 …
=> fix(Accordion): close other items in circular order

src/runtime/components/elements/Link.vue, src/runtime/types/link.d.ts
=> feat(Link): add `active` prop to override default behaviour

docs/components/content/examples/TableExampleStyle.vue, docs/content/4.data/1.table.md, src/runtime/components/data/Table.vue
Resolves #736
Add the ability to apply custom styles to `tr` and `td` elements by passing a `class` to rows.
=> feat(Table): add ability to custom style for  `td` and  `tr`

docs/content/1.getting-started/4.shortcuts.md
The items parameter of the UDropdown component is incorrect
=> docs(shortcuts): invalid dropdown items

docs/content/6.overlays/6.notification.md
Resolves #785
- Due to tailwind merge strategy introduced in #692, this caused `bottom-0` to be unexpectedly 'merged' in, following the use of the suggested `position: 'top-0 right-0'` ui configuration in the current doc.
=> docs: update `ui.notifications` position configuration

src/runtime/components/forms/Input.vue, src/runtime/components/forms/Textarea.vue
https://github.com/nuxt/ui/issues/815
A prop autofocusDelay that defaults to 100, this allows us to customize the setTimeout of focus() in the case we have page transitions
=> feat(Input/Textarea): allow specifying autofocus delay for page transitions

src/runtime/composables/usePopper.ts, src/runtime/composables/useUI.ts
With Nuxt v3.8 we require `verbatimModuleSyntax` (see https://github.com/nuxt/nuxt/pull/23447) and this PR fixes a type error that this will throw for projects using `@nuxt/ui` with the new version.
=> fix: use explicit type imports

src/runtime/components/data/Table.vue
While I was using the Table component I noticed that sorting did not work on nested column keys. I.e. when
defining a column like this:
```ts
{
key: 'creditor.name',
label: 'Creditor',
sortable: true,
}
```
Since the get function is already being imported, I made this small change.
Edit: Forgot to mention performance. This definitely affects performance to some degree but could possibly
be negligible in practice.
=> fix(Table): enable sorting for nested column keys

src/runtime/components/data/Table.vue
#646 #652
Reverts some of the changes made in #652.
Currently when checking the table header checkbox while the onSelect listener is used, onSelect is executed for every
row instead of just pushing the values to the selected Ref. This is an issue when onSelect  is used as suggested in the Docs:
`You can use this to navigate to a page, open a modal or even to select the row manually.`
In my use case the modal linked to the last item in the rows array will always open ( or many modals at once if implemented differently) and for navigation this is similar. There is no good way to prevent this as only the row is passed to onSelect. I think the checkbox state should not trigger onSelect. The other way around its fine imo and up to the user.
Edit: May be a breaking change to some existing …
=> fix(Table): prevent `@select` event call when selecting all rows

docs/components/content/examples/PaginationExampleFirstLastSlots.vue, docs/content/5.navigation/3.pagination.md, src/runtime/components/navigation/Pagination.vue, src/runtime/ui.config.ts
Resolves #837 
Added first and last page buttons to the pagination component to instantly jump to the last or first page. First and last page buttons are hidden by default and can be enabled with a boolean passed to the component.
=> feat(Pagination): add first and last page buttons

docs/content/1.getting-started/4.shortcuts.md
Added example usage for arrow keys in the keyboard shortcuts section of the docs (after spending a bit too long yesterday trying to figure out the correct syntax).
(This is my first time creating a PR - let me know if I've done something wrong!)
=> docs(shortcuts): add example usage for arrow keys

docs/components/content/examples/CommandPaletteExampleAsync.vue, docs/components/content/examples/CommandPaletteExampleFilter.vue, docs/content/5.navigation/2.command-palette.md, src/runtime/components/navigation/CommandPalette.vue, src/runtime/types/command-palette.d.ts
=> feat(CommandPalette): handle `filter` attribute in groups

docs/components/content/examples/TooltipExampleArrow.vue, docs/components/content/examples/TooltipExampleOffset.vue, docs/components/content/examples/TooltipExamplePlacement.vue, docs/content/6.overlays/4.tooltip.md, src/runtime/components/overlays/Tooltip.vue, src/runtime/composables/usePopper.ts, src/runtime/types/popper.d.ts, src/runtime/ui.config.ts
#836 
Added the option to include an arrow on the popper instance for the Tooltip component. It's optional, so no breaking changes.
Popper object prop doesn't have any documentation so I added a few examples on the Tooltip page.
Resolves #836
=> feat(Tooltip): adding option to show popper arrow

docs/components/content/examples/ContextMenuExampleArrow.vue, docs/components/content/examples/ContextMenuExampleOffset.vue, docs/components/content/examples/ContextMenuExamplePlacement.vue, docs/components/content/examples/DropdownExampleArrow.vue, docs/components/content/examples/DropdownExampleOffset.vue, docs/components/content/examples/DropdownExamplePlacement.vue, docs/components/content/examples/PopoverExampleArrow.vue, docs/components/content/examples/PopoverExampleOffset.vue, docs/components/content/examples/PopoverExamplePlacement.vue, docs/components/content/examples/SelectMenuExampleArrow.vue, docs/components/content/examples/SelectMenuExampleOffset.vue, docs/components/content/examples/SelectMenuExamplePlacement.vue, docs/content/2.elements/6.dropdown.md, docs/content/3.forms/4.select-menu.md, docs/content/6.overlays/3.popover.md, docs/content/6.overlays/4.tooltip.md, docs/content/6.overlays/5.context-menu.md, src/runtime/components/elements/Dropdown.vue, src/runtime/components/forms/SelectMenu.vue, src/runtime/components/overlays/ContextMenu.vue, src/runtime/components/overlays/Popover.vue, src/runtime/ui.config.ts
#873 
Adding the arrow option to all components that use popper. This provides consistent popper options across these components. Docs for each of these components have been updated to demonstrate how to use the `popper` prop.
Resolves #873
=> feat(popper): `arrow` option & docs consistency across components

src/runtime/components/elements/Dropdown.vue
=> fix(Dropdown): use `NuxtLink` instead of `ULink`

src/runtime/components/forms/Radio.vue
#893 
This is fixing the Radio help text from inlining with the label.
Resolves #893
=> fix(Radio): prevent `help` text from inlining with label

src/templates.ts
This fixes an error showing up (reproducible in this repo in `docs/` folder along these lines):
```
ERROR  EISDIR: illegal operation on a directory, read /nuxt/ui/docs/.nuxt
```
The issue is that the alias was wrongly set to `buildDir` (`.nuxt`) rather than the actual file.
=> fix(module): use correct alias for `#ui-colors`

src/runtime/components/forms/RadioGroup.vue, src/runtime/composables/useFormGroup.ts
#906 
This removes the auto-generated ID on the FormGroup element for Inputs containing a fieldset (e.g. RadioGroup) since they introduce their own labels and don't bind to the one provided by the FormGroup.
=> fix(FormGroup): remove inputId if the input is a fieldset

docs/app.vue, docs/error.vue
This is causing nuxt/ecosystem-ci to fail: see https://github.com/nuxt/ecosystem-ci/actions/runs/6741450354/job/18335361004.
🚨 **Actually, even with this fix it will still fail as `/pro` gives a 404 - page not found.** So it may not be the right fix here.
=> docs: don't add pro path if it doesn't exist

src/runtime/components/overlays/Notifications.vue
Fixes #904  
Notifications cant be clicked when another overlay is open(e.g. slideover). using `Teleport` allow user to click on notifiaction.
<details>
<summary>without teleport</summary>
https://github.com/arashsheyda/nuxt-ui/assets/38922203/99ccdade-356d-4a2c-98a8-bc611b75de19
</details>
<details>
<summary>with teleport</summary>
https://github.com/arashsheyda/nuxt-ui/assets/38922203/8a56b84a-c1c2-4176-adc4-6b32ee36daef
</details>
=> fix(Notifications): teleport to `body`

src/runtime/components/elements/Progress.vue
Fixes #938 
When the `value` exceeds the custom `max` value percent will be 100.
=> fix(Progress): percentage calculation

docs/content/3.forms/7.toggle.md, src/runtime/components/forms/Toggle.vue, src/runtime/ui.config.ts
#224 
This change adds a `size` prop to the Toggle component, allowing for users to choose their desired size. Documentation has been updated to show new prop
Resolves #224
=> feat(Toggle): add `size` prop

src/runtime/composables/defineShortcuts.ts
Fixes #954 
Here is a fix to the `-` shortcut using `defineShortcuts`, which has been broken when chained shortcuts were introduced.
Though, it fixes a bug but leverages some issues on more advanced usecases (complex keys).
The current separators for combined and chained shortcuts are `_` and `-`. And their combination in the same key is quite complex.
We could image being able to handle `_-_` (two hits on `_`), or `e_-` (combination of `e` and `-`). A non-exhaustive list of shortcuts that should work IMO: `['e_-', 'e__', '_-_', '---', '_--']`.
But let's fix this current issue and potentially create a new one for advanced shortcuts, or wait to see if the demand actually exists.
=> fix(defineShortcuts): support minus `-` key

src/runtime/components/navigation/CommandPalette.vue
Fixes https://github.com/nuxt/ui/issues/980
When using a group with async search in `<CommandPalette>` groups, the first item is not activated when the async search function resolves.
This PR activate the first option after async search in the `<CommandPalette>`, and reformat the code to use the same method `activateFirstOption`:
- in the `onMounted` function (when using `autoselect` prop)
- when the query changes (in the `watch` function)
- in the `debouncedSearch` callback.
=> fix(CommandPalette): activate first option after async search

docs/components/content/examples/VerticalNavigationExampleIconSlot.vue
none
Fix the `label` displaying beyond the container in the `VerticalNavigationExampleIconSlot` on mobile devices.
- Before
- After
=> docs(VerticalNavigation): add `truncate` in icon slot example

docs/components/content/ComponentCard.vue
#880 
Sorting the size options across the documentation. Resolves #880
=> docs: sort component `size` prop

docs/content/3.forms/4.select-menu.md, src/runtime/components/forms/SelectMenu.vue, src/runtime/ui.config.ts
Resolves #883
Currently, `<USelectMenu>` doesn't clear the search query when an option is selected, or when the menu is closed by selection.
This allows to clear it when the menu is closed, by either manually closing it or selecting an option, by using the attribute `clear-search-on-close`.
=> feat(SelectMenu): allows to clear search query on close

docs/components/content/examples/SelectMenuExampleSearchAttributes.vue, docs/content/3.forms/4.select-menu.md, src/runtime/components/forms/SelectMenu.vue
Currently, `<USelectMenu>` attribute `search-attributes` doesn't work when the property to search is a non-string, or is nested.
This fixes that behavior:
- The attribute uses the `get` internal utility to find the nested attribute if it's not a string or number.
- It uses the `String` constructor to cast the Object/Array option to a string.
=> fix(SelectMenu): fixes non-strings and nested searchable attributes

docs/content/1.getting-started/3.theming.md, src/module.ts
Fixes #1002
Resolves #1010
In your `nuxt.config.ts`, the `ui.icons` option can now be an object to completely override the options of the `@egoist/tailwindcss-icons` plugin:
```ts [nuxt.config.ts]
import { getIconCollections } from '@egoist/tailwindcss-icons'
export default defineNuxtConfig({
ui: {
icons: {
// might solve stretch bug on generate, see https://github.com/egoist/tailwindcss-icons/issues/23
extraProperties: {
'-webkit-mask-size': 'contain',
'-webkit-mask-position': 'center'
},
collections: {
foo: {
icons: {
'arrow-left': {
// svg body
body: '<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18" />',
// svg width and height, optional
width: 24,
height: 24
}
}
}, …
```
=> feat(module): allow options override of `@egoist/tailwindcss-icons` plugin

src/runtime/ui.config/navigation/breadcrumb.ts
N/A
This adds the left variant of the default divider icon in rtl 
**Before**
**After**
=> fix(Breadcrumb): handle divider in rtl

src/runtime/composables/useShortcuts.ts
No
Fixed that shortcuts can be used when a `contenteditable="plaintext-only"` element is focused.
[MDN Docs for contenteditable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable)
=> fix(useShortcuts): include `contenteditable="plaintext-only"` elements in `usingInput`

src/runtime/components/forms/Form.vue
[Issue #1164](https://github.com/nuxt/ui/issues/1164)
The current implementation of the clear function would set the errors ref to the result of a filter on the errors ref. However the test was checking if the errors path was equal to the path passed to the clear function. This results in all other form errors being cleared except for the error(s) that have the specified path, which is opposite of the docs say: "Clears form errors associated with a specific path. If no path is provided, clears all form errors.".
So I just set the filters test to filter all errors that has a path not equal to the path passed in to the clear function.
```ts
clear (path?: string) {
if (path) {
errors.value = errors.value.filter((err) => err.path !== path)
} else {
errors.value = []
}
}
```
Resolves #1164
=> fix(Form): invalid errors when using `clear` by path

docs/content/3.forms/10.form.md, src/runtime/components/forms/Form.vue, src/runtime/types/form.d.ts
=> feat(Form): expose submit function

src/runtime/components/forms/Form.vue, src/runtime/utils/uid.ts
Resolves #1081
Fixes memory leak in form component by capping the maximum uid value to MAX_SAFE_INTEGER and properly destroying event listeners.
=> fix(Form): memory leak

src/runtime/components/elements/Accordion.vue
This adds type assertions for these event listeners, needed for upgrade to vue 3.4.4. Discovered in https://github.com/nuxt/ecosystem-ci/actions/runs/7395824181/job/20124645666.
I would recommend adding something to confirm that `_el` is in fact an HTML element rather than just asserting it.
=> chore(Accordion): match event listener types

docs/nuxt.config.ts
failing ecosystem-ci test: https://github.com/nuxt/ecosystem-ci/actions/runs/7426329650/job/20210099666
This allows us to ignore `/pro` path when it can't be generated (when missing certain tokens, like in ecosystem CI)...
=> docs: ignore `/pro` when no token is provided

src/runtime/ui.config/overlays/slideover.ts
Update the Slideover translate config to solve the translate animation directions in RTL.
Resolves #1258 
Added RTL translate styles for the Slideover component to handle translation in rtl direction
=> fix(Slideover): handle translate in RTL mode

docs/content/3.forms/10.form.md, src/runtime/components/forms/Form.vue
The primary motivation behind this change is to address a specific use case where multiple dynamic paths need validation for a multi-step form. In the original implementation, when a user progressed to the next step by clicking "continue," I needed to validate various steps asynchronously. The solution involved using await Promise.all(paths.map(path => form.value.validate(path))).
However, due to the asynchronous nature of the validate function, there was a potential issue where the final state of errors.value might not accurately reflect the expected validation results.
=> feat(Form): handle multiple paths in `validate`

docs/components/content/examples/CarouselExample.vue, docs/components/content/examples/CarouselExampleArrows.vue, docs/components/content/examples/CarouselExampleArrowsCenter.vue, docs/components/content/examples/CarouselExampleIndicators.vue, docs/components/content/examples/CarouselExampleIndicatorsSize.vue, docs/components/content/examples/CarouselExampleSize.vue, docs/components/content/examples/CarouselExampleSizeCenter.vue, docs/components/content/examples/CarouselExampleSizeFull.vue, docs/components/content/examples/CarouselExampleSlotsDefault.vue, docs/components/content/examples/CarouselExampleSlotsIndicator.vue, docs/components/content/examples/CarouselExampleSlotsPrevNext.vue, docs/components/content/examples/CarouselExampleSnapEnd.vue, docs/components/content/examples/CarouselExampleSnapStart.vue
Added `draggable="false"` to the image element to allow dragging the carousel with the mouse.
https://github.com/nuxt/ui/assets/33054273/f313e7bd-5d3f-4782-88de-99513732cae1
=> docs(Carousel): add `draggable="false"` to image elements

docs/content/2.components/textarea.md, src/runtime/components/forms/Textarea.vue
In the current state, `Textarea` component with the `autoresize` prop will grow infinitely.
This pull request aims to add a new prop letting developers to define a maximum number of rows a `Textarea` can grow.
If set to 0 (which is also the default value), it will preserve the current `autoresize` behavior.
I didn't manage to start the local development environment for the docs because of the required nuxt ui pro license so I didn't check if my changes to `ui/docs/content/2.components/textarea.md` are correct.
https://github.com/nuxt/ui/assets/46727566/3d567605-8421-427b-89f9-993b07ede257
=> feat(Textarea): add `maxrows` prop to restrict autoresize

docs/content/2.components/table.md, src/runtime/components/data/Table.vue, src/runtime/ui.config/data/table.ts
Resolves #1028 
A [Progress](https://ui.nuxt.com/components/progress) will now be displayed when the `loading` prop is `true`.
Also, the `loadingState` will now only be displayed when no rows are provided to prevent flicker.
=> feat(Table): display progress bar when `loading`

src/runtime/types/form.d.ts
Fixes #1369
This pull request resolves the type mismatch error that occurs in the form validate.
=> fix(Form): improve `validate` path type

docs/content/2.components/select-menu.md
Fix anchor link in [SelectMenu](https://ui.nuxt.com/components/select-menu) page
=> docs(SelectMenu): invalid anchor to `creatable`

docs/content/2.components/form-group.md
the icon does not match the code example
=> docs(FormGroup): wrong icon name in `#help` slot

docs/content/2.components/link.md
This adds a section to the Link component suggesting that it's possible to add 2 new  strings into `tailwindCSS.classAttributes` in `.vscode/settings.json` in order to have intellisense Tailwind suggestions.
=> docs(Link): add `IntelliSense` section

docs/content/2.components/notification.md
[notification](https://ui.nuxt.com/components/notification) mentions about `UNotifications` but doesn't enlist it's props and config which is different than `UNotification`
=> docs(Notification): add `Notifications` props and config

.nuxtrc
https://github.com/nuxt/ecosystem-ci/actions/runs/8210272012/job/22462705680
Since https://github.com/unjs/nitro/pull/2226, new nitropack version will throw an error when type checking because we explicitly disable autoImports for all packages (including docs) in the workspace.
However, this should be safe to disable as the module uses new module-builder prepare mode which generates a `.nuxt/tsconfig.json` with autoImports already disabled (for root package) but doesn't affect playground + docs.
=> chore: remove auto-import override

src/runtime/components/forms/Checkbox.vue, src/runtime/components/forms/Radio.vue
Resolves #1485 
Bind `data-n-ids` attribute to root element of the Checkbox component to fix hydration mismatch caused by using useId with `inheritAttrs: false`.
=> fix(Checkbox): bind `data-n-ids` to root element

src/runtime/components/elements/Carousel.vue
Resolves #1484.
According to the W3C ARIA Authoring Practices Guide, specifically [the page on the Carousel pattern](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/#wai-ariaroles,states,andproperties) using tab-based ARIA roles is one of the suggested uses of ARIA. This uses that ARIA pattern for the specific Carousel use-case with indicators (as that is what the APA is talking about when it refers to a "tabbed" carousel).
=> fix(Carousel): add tab-based ARIA roles

src/runtime/composables/useButtonGroup.ts
Resolves #1425 
Updating the `useButtonGroup` composable to take into account if a parent has already consumed the `ButtonGroupContext`. If so, then the current child should not also consume that same context.
=> fix(ButtonGroup): nested group elements

src/runtime/components/elements/Dropdown.vue, src/runtime/components/overlays/Popover.vue
Resolves #1512
Change from prevent to passive ontouchstart event.
To fix the bug: [Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
=> fix(Popover/Dropdown): use `@touchstart.passive` instead of `@touchstart.prevent`

src/runtime/components/forms/SelectMenu.vue
Resolves #1540 
In the `SelectMenu.vue` file, there's this snippet where it checks for `filteredOptions.length`
```vue
<p v-else-if="searchable && query && !filteredOptions.length" :class="uiMenu.option.empty">
<slot name="option-empty" :query="query">
No results for "{{ query }}".
</slot>
</p>
<p v-else-if="!filteredOptions.length" :class="uiMenu.empty">
<slot name="empty" :query="query">
No options.
</slot>
</p>
```
But because `filteredOptions` is a `computedAsync`, there's a possibility that the object itself is still undefined, thus checking for `.length` will not be possible.
```
SelectMenu.vue:652 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
at SelectMenu.vue:652:52
at Proxy.renderFnWithContext (vue.js?v=74953c0b:2286:13)
at y …
```
=> fix(SelectMenu): `filteredOptions` might be undefined

docs/components/content/examples/DatePickerExample.vue
Resolves #1461 
Add is-required prop to DatePicker component
=> docs(DatePicker): add `is-required` prop

src/runtime/components/elements/Accordion.vue
NA
This PR introduces a new event for `UAccordion` so that a user can listen to when an accordion item was opened.
This could allow the user to lazy load an accordion item's content when opened, for example.
=> feat(Accordion): emit `open` event with index

docs/content/2.components/toggle.md, src/runtime/components/forms/Toggle.vue, src/runtime/ui.config/forms/toggle.ts
Use the loading prop to show a loading icon and disable the Toggle.
I want to change state of toggle by calling api, naive-ui has this one!
=> feat(Toggle): add `loading` prop

src/runtime/components/forms/Checkbox.vue, src/runtime/components/forms/Input.vue, src/runtime/components/forms/InputMenu.vue, src/runtime/components/forms/Radio.vue, src/runtime/components/forms/Range.vue, src/runtime/components/forms/Select.vue, src/runtime/components/forms/SelectMenu.vue, src/runtime/components/forms/Textarea.vue, src/runtime/components/forms/Toggle.vue
Resolves #1113
Normalize input emits, especially for the change event. This PR includes a small breaking change on the `URange`, `USelect` and `UCheckbox` components: the change event's payload is now the input's value instead of the HTML event to match other inputs.
=> fix(forms)!: normalize input emits

src/runtime/components/forms/Input.vue, src/runtime/components/forms/SelectMenu.vue
=> fix(Input/SelectMenu): handle `file` type and `change` events

docs/content/1.getting-started/2.installation.md
NA
With the introduction of [`@nuxt/eslint`](https://github.com/nuxt/eslint), their base linting rules make `/*ui*/` invalid and forces us to write `/* ui */`instead.
This change adds an optional whitespace around `ui` so that the linter does not complain, and the class regex to still work as expected.
=> docs(installation): update regex to match `@nuxt/eslint` rules

docs/content/1.getting-started/2.installation.md
closed #1554 , related #1606 .
Added use`nuxi init` command to installation section.
=> docs: use `nuxi init -t ui` command in installation

src/runtime/components/overlays/Notification.vue
Resolves https://github.com/nuxt/ui/issues/1667
In between a fix and an enhancement
Following #1668 , when updating the timeout prop, the behavior is not the expected behavior from a user perspective. When updating the `timeout` prop, the timer should reset and apply the new timeout.
=> fix(Notification): update timer when timeout prop changes

src/runtime/components/data/Table.vue
Table headings should have the Aria attribute `aria-sort` set.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-sort
=> fix(Table): provide `aria-sort` for sortable table headings

docs/components/content/examples/PaginationExampleTo.vue, docs/content/2.components/pagination.md, src/runtime/components/navigation/Pagination.vue
Resolves #1478 
This change allows buttons in the pagination to become links, and be detected by crawlers
> [!NOTE]  
> Playground commits should be removed and are here just for demo purpose
> [!WARNING]  
> In the demo, the link behave weirdly: it refreshes the whole page instead of just modifying the query
=>  feat(Pagination): allow using links for pagination buttons 

src/runtime/types/slideover.d.ts
This allows importing the slideover props if needed when building higher order components.
=> fix(Slideover): export and clean types

docs/content/2.components/input.md, src/runtime/components/forms/Input.vue, src/runtime/ui.config/forms/input.ts
Resolves #1524, resolves #1412
=> fix(Input)!: redesign `file` type without absolute positioning

docs/content/2.components/input-menu.md, docs/content/2.components/select-menu.md, src/runtime/components/forms/InputMenu.vue, src/runtime/components/forms/SelectMenu.vue
Resolves #1686 
Maybe we need a  `searchableLazy` switch to achieve optimization goals.
Use the `searchableLazy` prop to control the immediacy of data requests.
=> feat(InputMenu/SelectMenu): allow lazy search
