docs/content/3.forms/2.textarea.md
Completes the current `Textarea` props documentation.
=> docs(textarea): improve props documentation

docs/components/content/examples/CommandPaletteExampleEmptySlot.vue, docs/content/5.navigation/2.command-palette.md, src/runtime/components/navigation/CommandPalette.vue
=> feat(CommandPalette): handle `empty-state`

docs/plugins/ui.ts, src/runtime/plugins/colors.ts, src/runtime/utils/index.ts
The `hexToRgb` method is missing a type declaration for its parameter.
=> chore(utils): types

src/runtime/app.config.ts, src/runtime/components/elements/ButtonGroup.ts
We have noticed a few problems with RTL languages, here are what we have changed:
- change all margin, padding, and border-radius to the new logical property utilities introduced in Tailwind v3.3 (https://tailwindcss.com/blog/tailwindcss-v3-3) to support both LTR and RTL languages
- change all text direction text-left to rtl:text-right ltr:text-left
=> feat: RTL support

README.md, docs/components/content/themes/LTRAndRTLTheme.vue, docs/content/1.getting-started/1.index.md, docs/content/1.getting-started/5.examples.md
I documented support for RTL and LTR on the starting page within the features section and added an example.
=> docs: add support for RTL and LTR

src/runtime/app.config.ts, src/runtime/components/elements/Accordion.vue
=> fix(Accordion): solve the shift between buttons when they are opened

docs/app.vue, docs/components/content/examples/NotificationExampleHtml.vue, docs/content/6.overlays/6.notification.md, src/runtime/components/overlays/Notification.vue, src/runtime/components/overlays/Notifications.vue
=> feat(Notification): support html with `title` and `description` slots

docs/content/7.layout/3.skeleton.md
Change `class="rounded-full"` to `:ui="{ rounded: 'rounded-full' }"`.
=> docs(Skeleton): Fix usage example

src/runtime/app.config.ts, src/runtime/components/forms/Range.vue
=> feat(Range): increase narrowed surface

src/runtime/components/data/Table.vue
=> fix(Table): hide data when loading state is active

docs/content/3.forms/10.form.md, src/runtime/types/form.d.ts
=> fix(Form): fix wrong type of validate. simplify example

docs/components/content/examples/ModalExampleFullscreen.vue, docs/content/6.overlays/1.modal.md, src/runtime/app.config.ts, src/runtime/components/overlays/Modal.vue
=> feat(Modal): add `fullscreen` prop

src/runtime/components/navigation/Tabs.vue
=> fix(Tabs): recompute marker position when `v-model` changes

src/runtime/components/data/Table.vue
=> fix(Table): empty state is displayed if null

docs/components/content/ComponentCard.vue
fix [#558](https://github.com/nuxtlabs/ui/issues/558)
=> docs: add colon before numeric props

src/runtime/app.config.ts
=> fix(Tooltip): hide tooltip on touch devices

src/runtime/app.config.ts
add 'overflow-x-auto' TailwindClass to make table responsive on smaller device
=> chore(Table): add `overflow-x-auto` to wrapper

src/runtime/components/navigation/Pagination.vue
Fix https://github.com/nuxt/ui/issues/623
=> fix(Pagination): fix page numbers not clickable

docs/pages/[...slug].vue
=> docs: broken `Edit this page` link

docs/app.vue, docs/components/BranchSelect.vue, docs/components/Header.vue, docs/composables/useContentSource.ts, docs/error.vue, docs/nuxt.config.ts, docs/package.json, docs/pages/[...slug].vue, docs/tailwind.config.ts, pnpm-lock.yaml
=> docs: improve multi-source handling

docs/components/content/ComponentCard.vue, docs/components/content/ComponentExample.vue
fixed #748
Use the default return value of the `getHighlightedAST` function, by https://github.com/nuxt-modules/mdc/blob/main/src/runtime/shiki/highlighter.ts#L97-L102
=> docs(ComponentCard): fix inline highlighter

docs/components/Footer.vue, docs/pages/[...slug].vue
Added discord link to the section community
=> docs: add discord link to the section community

docs/content/3.forms/10.form.md
=> docs: add link to the `FormExampleElements`

docs/components/content/examples/FormExampleBasic.vue, docs/components/content/examples/FormExampleElements.vue, docs/components/content/examples/FormExampleJoi.vue, docs/components/content/examples/FormExampleValibot.vue, docs/components/content/examples/FormExampleYup.vue, docs/components/content/examples/FormExampleZod.vue, docs/content/3.forms/10.form.md
- No need to import `ref` with Nuxt.
- The first example was broken since we check `state.license` instead of `state.value.license`, best is to use `reactive()` instead IMO
- Added the example of using `$fetch` instead of `fetch`
=> docs: improve form docs

package.json
to add https://ui.nuxt.com here : https://www.npmjs.com/package/@nuxt/ui
=> chore(package): add `homepage`

src/runtime/components/forms/Checkbox.vue, src/runtime/components/forms/FormGroup.vue, src/runtime/components/forms/Radio.vue, src/runtime/composables/useFormGroup.ts
=> fix(FormGroup): hydration mismatch on inputId

docs/content/1.getting-started/4.shortcuts.md, docs/package.json, package.json, pnpm-lock.yaml, src/runtime/composables/defineShortcuts.ts
This fixes an internal issue with `Boolean` (which is the type of a constructor, e.g. `() => boolean`) -> `boolean` (which is the 'raw' type).
I also update to Nuxt v3.8.2.
=> fix(module): `boolean` types and bump nuxt to `3.8.2`

src/runtime/components/overlays/Notification.vue, src/runtime/ui.config.ts
Allow the customization of the default timeout for Notifications.
=> feat(Notification): customize default timeout

docs/components/content/examples/FormExampleElements.vue, docs/components/content/examples/InputMenuExampleBasic.vue, docs/components/content/examples/InputMenuExampleEmptySlot.vue, docs/components/content/examples/InputMenuExampleObjects.vue, docs/components/content/examples/InputMenuExampleObjectsValueAttribute.vue, docs/components/content/examples/InputMenuExampleOptionEmptySlot.vue, docs/components/content/examples/InputMenuExampleOptionSlot.vue, docs/components/content/examples/InputMenuExamplePopperArrow.vue, docs/components/content/examples/InputMenuExamplePopperOffset.vue, docs/components/content/examples/InputMenuExamplePopperPlacement.vue, docs/components/content/examples/InputMenuExampleSearchAttributes.vue, docs/content/3.forms/1.input.md, docs/content/3.forms/2.input-menu.md, docs/content/3.forms/3.select.md, src/runtime/components/forms/InputMenu.vue, src/runtime/ui.config/forms/input.ts, src/runtime/ui.config/forms/inputMenu.ts, src/runtime/ui.config/forms/selectMenu.ts, src/runtime/ui.config/index.ts, src/runtime/ui.config/popper.ts
=> feat(InputMenu): new component

package.json, pnpm-lock.yaml, src/runtime/components/data/Table.vue, src/runtime/components/forms/Form.vue
[Caught by ecosystem CI](https://github.com/nuxt/ecosystem-ci/actions/runs/7233707958/job/19709288613), there are some type issues within `nuxt/ui` that will be revealed in next vue release. This bumps vue version and addresses them.
=> fix: update vue and fix type issues

docs/content/1.getting-started/2.installation.md
There was no command for installation with Bun. In other libraries in the Vue ecosystem, there are instructions for Bun, so it would be good for consistency to add it there too.
=> docs(installation): add `bun` command

docs/content/6.overlays/6.notification.md
#1180 
Add the default timeout value for notification, to the docs
Serves as a reference point while trying to adjusting the value
=> docs(notification): add default timeout value

docs/pages/releases.vue
This allows generating the documentation without a github token (as seems intended by the fact that the api routes return an empty array). This allows us to run the docs build step as a test in nuxt/ecosystem-ci without passing a token in.
=> docs: allow generating docs without github token

docs/content/1.getting-started/2.installation.md
I fixed a typo in the documentation.
=> docs(installation): typo

src/tailwind.ts
Quick minor fix about code I noticed!
=> chore(tailwind): put empty object in quotes

docs/components/content/ComponentCard.vue, docs/components/content/ComponentExample.vue, docs/package.json, package.json, pnpm-lock.yaml
This PR can be pended until next version of Content module.
Refactor custom Shiki highlighter in the example due to a breaking change in `@nuxtjs/mdc@0.4.0`.
=> docs(deps): update `@nuxt/content`

docs/content/2.components/table.md
This PR addresses a small grammatical issue in the documentation. A word was missing from the sentence.
=> docs(table): correct spelling

src/runtime/components/forms/Form.vue, src/runtime/types/form.d.ts
=> fix(Form): return false when silent validation fails

docs/content/2.components/form.md
This improves the form documentation for improved clarity and readability.
=> docs(form): improve form documentation

docs/content/2.components/breadcrumb.md
=> docs(breadcrumb): add link to github

src/runtime/components/forms/Checkbox.vue
=> fix(Checkbox): label interaction without `FormGroup`

docs/content/2.components/date-picker.md
=> docs(date-picker): include `date-fns` in installation

src/runtime/ui.config/overlays/modal.ts
Resolves #1459, resolves nuxt-ui-pro/dashboard#7
Changed overflow style form Modal component
=> fix(Modal): remove `overflow-hidden`

docs/content/1.getting-started/1.index.md
=> docs(getting-started): grammar correction

docs/.nuxtrc, package.json, playground/.nuxtrc, tsconfig.json
https://github.com/nuxt/ui/pull/1492
https://github.com/nuxt/ecosystem-ci/actions/runs/8210272012/job/22470189909
Sorry, one more chore to fix type checking in ecosystem CI.
=> chore: check playground types separately

docs/content/2.components/icon.md
🔗 Linked issue
❓ Type of change
📝 Checklist
=> docs(icon): add link to theming icons section

src/runtime/components/data/Table.vue, src/runtime/components/forms/Checkbox.vue
Resolves #1578 
Fix the value emitted empty value by checkbox onChange
=> fix(Checkbox): `@change` event value

src/runtime/composables/useToast.ts
Resolves #1667 
Add a new method to `useToast` to update a notification. Note that updating the id will recreate the notification.
=>  feat(useToast): allow updating an existing notification 

README.md
Adding a module manually is no longer required when using `nuxi module add`.
=> chore(README): update installation section

docs/components/content/examples/TableExampleCaptionSlot.vue, docs/content/2.components/table.md, src/runtime/components/data/Table.vue, src/runtime/ui.config/data/table.ts
Allow users to provide the table a caption. https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#5
=> feat(Table): allow providing a `<caption>`
